"""Wide-signal Cython section generators for CythonCodegen."""

from __future__ import annotations

from veriforge.sim.compiled._codegen_utils import _WORD_BITS


class _GenWideSectionsMixin:
    """Mixin providing wide-signal Cython section builders for CythonCodegen."""

    __slots__ = ()

    def _gen_wide_primitives(self) -> str:
        """Emit pure word-loop primitive functions into the generated preamble.

        These functions have no SimCtx dependency — they operate on raw
        (unsigned long long *) val/mask pointer pairs.  They are emitted only
        when the module has wide (>64-bit) state.
        """
        if not self._module_has_wide_state():
            return ""

        L: list[str] = [
            "# ── Wide-value primitives ──────────────────────────────────────────────────",
            "# Pure word-loop computation on (val, mask) array pairs.",
            "# No SimCtx pointer — callers manage scratch pointers.",
            "",
        ]

        # ── wide_copy ──────────────────────────────────────────────────────────
        L += [
            "cdef inline void wide_copy(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, remaining_w",
            "    cdef unsigned long long tail_mask",
            "    for i in range(n):",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] = (av[i] & ~am[i]) & tail_mask",
            "        dm[i] = am[i] & tail_mask",
            "",
        ]

        # ── wide_and ───────────────────────────────────────────────────────────
        # 4-state: x & 0 = 0, x & 1 = x, x & x = x
        L += [
            "cdef inline void wide_and(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, remaining_w",
            "    cdef unsigned long long tail_mask, lv, lm, rv, rm, def0, out_m, out_v",
            "    for i in range(n):",
            "        lv = av[i]; lm = am[i]; rv = bv[i]; rm = bm[i]",
            "        def0 = (~lv & ~lm) | (~rv & ~rm)",
            "        out_m = (lm | rm) & ~def0",
            "        out_v = lv & rv & ~out_m",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] = out_v & tail_mask",
            "        dm[i] = out_m & tail_mask",
            "",
        ]

        # ── wide_or ────────────────────────────────────────────────────────────
        # 4-state: x | 1 = 1, x | 0 = x, x | x = x
        L += [
            "cdef inline void wide_or(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, remaining_w",
            "    cdef unsigned long long tail_mask, lv, lm, rv, rm, def1, out_m, out_v",
            "    for i in range(n):",
            "        lv = av[i]; lm = am[i]; rv = bv[i]; rm = bm[i]",
            "        def1 = (lv & ~lm) | (rv & ~rm)",
            "        out_m = (lm | rm) & ~def1",
            "        out_v = (lv | rv) & ~out_m",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] = out_v & tail_mask",
            "        dm[i] = out_m & tail_mask",
            "",
        ]

        # ── wide_xor ───────────────────────────────────────────────────────────
        L += [
            "cdef inline void wide_xor(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, remaining_w",
            "    cdef unsigned long long tail_mask, lv, lm, rv, rm, out_m, out_v",
            "    for i in range(n):",
            "        lv = av[i]; lm = am[i]; rv = bv[i]; rm = bm[i]",
            "        out_m = lm | rm",
            "        out_v = (lv ^ rv) & ~out_m",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] = out_v & tail_mask",
            "        dm[i] = out_m & tail_mask",
            "",
        ]

        # ── wide_not ───────────────────────────────────────────────────────────
        L += [
            "cdef inline void wide_not(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, remaining_w",
            "    cdef unsigned long long tail_mask",
            "    for i in range(n):",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] = (~av[i] & ~am[i]) & tail_mask",
            "        dm[i] = am[i] & tail_mask",
            "",
        ]

        # ── wide_neg (two's complement) ────────────────────────────────────────
        # Any x/z in source → result is all-x.
        L += [
            "cdef inline void wide_neg(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, has_x, remaining_w",
            "    cdef unsigned long long tail_mask, nw, carry, s",
            "    has_x = 0",
            "    for i in range(n):",
            "        if am[i] != 0:",
            "            has_x = 1",
            "            break",
            "    if has_x:",
            "        for i in range(n):",
            "            remaining_w = dst_width - i * 64",
            "            tail_mask = _word_mask64(remaining_w)",
            "            dv[i] = 0",
            "            dm[i] = tail_mask",
            "        return",
            "    carry = 1",
            "    for i in range(n):",
            "        nw = ~av[i]",
            "        s = nw + carry",
            "        carry = 1 if s < nw else 0",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] = s & tail_mask",
            "        dm[i] = 0",
            "",
        ]

        # ── wide_add (multi-word addition) ─────────────────────────────────────
        # Any x/z in either operand → result is all-x.
        L += [
            "cdef inline void wide_add(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, has_x, remaining_w",
            "    cdef unsigned long long tail_mask, lv, rv, s1, s2, carry",
            "    has_x = 0",
            "    for i in range(n):",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "            break",
            "    if has_x:",
            "        for i in range(n):",
            "            remaining_w = dst_width - i * 64",
            "            dv[i] = 0",
            "            dm[i] = _word_mask64(remaining_w)",
            "        return",
            "    carry = 0",
            "    for i in range(n):",
            "        lv = av[i]; rv = bv[i]",
            "        s1 = lv + rv",
            "        s2 = s1 + carry",
            "        carry = 1 if (s1 < lv or s2 < s1) else 0",
            "        remaining_w = dst_width - i * 64",
            "        dv[i] = s2 & _word_mask64(remaining_w)",
            "        dm[i] = 0",
            "",
        ]

        # ── wide_sub (multi-word subtraction: av - bv) ─────────────────────────
        L += [
            "cdef inline void wide_sub(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, has_x, remaining_w",
            "    cdef unsigned long long tail_mask, lv, rv, tmp, borrow",
            "    has_x = 0",
            "    for i in range(n):",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "            break",
            "    if has_x:",
            "        for i in range(n):",
            "            remaining_w = dst_width - i * 64",
            "            dv[i] = 0",
            "            dm[i] = _word_mask64(remaining_w)",
            "        return",
            "    borrow = 0",
            "    for i in range(n):",
            "        lv = av[i]; rv = bv[i]",
            "        tmp = rv + borrow",
            "        borrow = 1 if (tmp < rv or lv < tmp) else 0",
            "        remaining_w = dst_width - i * 64",
            "        dv[i] = (lv - tmp) & _word_mask64(remaining_w)",
            "        dm[i] = 0",
            "",
        ]

        # ── wide_shl (logical left shift by constant) ──────────────────────────
        # x/z bits follow the shift pattern; no additional x-propagation.
        L += [
            "cdef inline void wide_shl(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int amount, int n, int dst_width) noexcept nogil:",
            "    cdef int i, src_hi, src_lo, remaining_w",
            "    cdef int wshift = amount >> 6",
            "    cdef int bshift = amount & 63",
            "    cdef unsigned long long hi_v, lo_v, hi_m, lo_m",
            "    for i in range(n):",
            "        src_hi = i - wshift",
            "        src_lo = src_hi - 1",
            "        hi_v = (av[src_hi] << bshift) if 0 <= src_hi < n else 0",
            "        hi_m = (am[src_hi] << bshift) if 0 <= src_hi < n else 0",
            "        if bshift > 0 and 0 <= src_lo < n:",
            "            lo_v = av[src_lo] >> (64 - bshift)",
            "            lo_m = am[src_lo] >> (64 - bshift)",
            "        else:",
            "            lo_v = 0",
            "            lo_m = 0",
            "        remaining_w = dst_width - i * 64",
            "        dv[i] = (hi_v | lo_v) & _word_mask64(remaining_w)",
            "        dm[i] = (hi_m | lo_m) & _word_mask64(remaining_w)",
            "",
        ]

        # ── wide_shr (logical right shift by constant) ─────────────────────────
        L += [
            "cdef inline void wide_shr(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int amount, int n, int dst_width) noexcept nogil:",
            "    cdef int i, src_lo, src_hi, remaining_w",
            "    cdef int wshift = amount >> 6",
            "    cdef int bshift = amount & 63",
            "    cdef unsigned long long lo_v, hi_v, lo_m, hi_m",
            "    for i in range(n):",
            "        src_lo = i + wshift",
            "        src_hi = src_lo + 1",
            "        lo_v = (av[src_lo] >> bshift) if 0 <= src_lo < n else 0",
            "        lo_m = (am[src_lo] >> bshift) if 0 <= src_lo < n else 0",
            "        if bshift > 0 and 0 <= src_hi < n:",
            "            hi_v = av[src_hi] << (64 - bshift)",
            "            hi_m = am[src_hi] << (64 - bshift)",
            "        else:",
            "            hi_v = 0",
            "            hi_m = 0",
            "        remaining_w = dst_width - i * 64",
            "        dv[i] = (lo_v | hi_v) & _word_mask64(remaining_w)",
            "        dm[i] = (lo_m | hi_m) & _word_mask64(remaining_w)",
            "",
        ]

        # ── wide_ashr (arithmetic right shift by constant) ─────────────────────
        # Fills vacated high bits with the sign bit of the source.
        # Matches VM semantics: if any source bit is X, result is all-X.
        L += [
            "cdef inline void wide_ashr(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int amount, int n, int src_width, int dst_width) noexcept nogil:",
            "    cdef int i, src_lo, src_hi, sign_word, sign_pos, valid_bits, has_x",
            "    cdef int fill_start_word, fill_bit_in_word, remaining_w",
            "    cdef int wshift = amount >> 6",
            "    cdef int bshift = amount & 63",
            "    cdef unsigned long long lo_v, hi_v, lo_m, hi_m",
            "    cdef unsigned long long sign_v, sign_m, fill_v, fill_m, fill_mask",
            "    # VM semantics: any X bit in source → entire result is all-X",
            "    has_x = 0",
            "    for i in range(n):",
            "        if am[i]: has_x = 1; break",
            "    if has_x:",
            "        for i in range(n):",
            "            remaining_w = dst_width - i * 64",
            "            if remaining_w <= 0: break",
            "            dv[i] = 0",
            "            dm[i] = _word_mask64(remaining_w)",
            "        return",
            "    sign_word = (src_width - 1) >> 6",
            "    sign_pos  = (src_width - 1) & 63",
            "    if sign_word < n:",
            "        sign_v = (av[sign_word] >> sign_pos) & 1",
            "        sign_m = (am[sign_word] >> sign_pos) & 1",
            "    else:",
            "        sign_v = 0; sign_m = 0",
            "    fill_v = 0 if sign_v == 0 else <unsigned long long>-1",
            "    fill_m = 0 if sign_m == 0 else <unsigned long long>-1",
            "    valid_bits = src_width - amount",
            "    if valid_bits < 0:",
            "        valid_bits = 0",
            "    # Shift (same as wide_shr)",
            "    for i in range(n):",
            "        src_lo = i + wshift",
            "        src_hi = src_lo + 1",
            "        lo_v = (av[src_lo] >> bshift) if 0 <= src_lo < n else fill_v",
            "        lo_m = (am[src_lo] >> bshift) if 0 <= src_lo < n else fill_m",
            "        if bshift > 0:",
            "            if 0 <= src_hi < n:",
            "                hi_v = av[src_hi] << (64 - bshift)",
            "                hi_m = am[src_hi] << (64 - bshift)",
            "            else:",
            "                hi_v = fill_v << (64 - bshift)",
            "                hi_m = fill_m << (64 - bshift)",
            "        else:",
            "            hi_v = 0; hi_m = 0",
            "        remaining_w = dst_width - i * 64",
            "        dv[i] = (lo_v | hi_v) & _word_mask64(remaining_w)",
            "        dm[i] = (lo_m | hi_m) & _word_mask64(remaining_w)",
            "    # Fill the vacated high bits with sign",
            "    fill_start_word = valid_bits >> 6",
            "    fill_bit_in_word = valid_bits & 63",
            "    for i in range(fill_start_word, n):",
            "        remaining_w = dst_width - i * 64",
            "        if remaining_w <= 0:",
            "            break",
            "        fill_mask = _word_mask64(remaining_w)",
            "        if i == fill_start_word and fill_bit_in_word > 0:",
            "            fill_mask = fill_mask & ~_word_mask64(fill_bit_in_word)",
            "        dv[i] = (dv[i] & ~fill_mask) | (fill_v & fill_mask)",
            "        dm[i] = (dm[i] & ~fill_mask) | (fill_m & fill_mask)",
            "",
        ]

        # ── wide_slice_extract: dst = src[lsb +: width] ───────────────────────
        L += [
            "cdef inline void wide_slice_extract(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int lsb, int width, int n_src, int n_dst) noexcept nogil:",
            "    cdef int i, sw, remaining_w",
            "    cdef int src_word = lsb >> 6",
            "    cdef int src_shift = lsb & 63",
            "    cdef unsigned long long lo_v, hi_v, lo_m, hi_m",
            "    for i in range(n_dst):",
            "        sw = src_word + i",
            "        lo_v = av[sw] if 0 <= sw < n_src else 0",
            "        lo_m = am[sw] if 0 <= sw < n_src else 0",
            "        if src_shift > 0 and sw + 1 < n_src:",
            "            hi_v = av[sw + 1] << (64 - src_shift)",
            "            hi_m = am[sw + 1] << (64 - src_shift)",
            "        else:",
            "            hi_v = 0; hi_m = 0",
            "        remaining_w = width - i * 64",
            "        dv[i] = ((lo_v >> src_shift) | hi_v) & _word_mask64(remaining_w)",
            "        dm[i] = ((lo_m >> src_shift) | hi_m) & _word_mask64(remaining_w)",
            "",
        ]

        # ── wide_cmp_eq: 1-bit result written to dv[0]/dm[0] ──────────────────
        # dv[0]=1 if equal and no x/z; dv[0]=0 otherwise; dm[0]=1 if x/z present.
        L += [
            "cdef inline void wide_cmp_eq(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n) noexcept nogil:",
            "    cdef int i, has_x = 0, equal = 1",
            "    for i in range(n):",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "        if am[i] == 0 and bm[i] == 0 and (av[i] & ~am[i]) != (bv[i] & ~bm[i]):",
            "            equal = 0",
            "    dv[0] = 1 if (equal and not has_x) else 0",
            "    dm[0] = 1 if has_x else 0",
            "",
        ]

        # ── wide_cmp_ne ────────────────────────────────────────────────────────
        L += [
            "cdef inline void wide_cmp_ne(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n) noexcept nogil:",
            "    cdef int i, has_x = 0, equal = 1",
            "    for i in range(n):",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "        if am[i] == 0 and bm[i] == 0 and (av[i] & ~am[i]) != (bv[i] & ~bm[i]):",
            "            equal = 0",
            "    dv[0] = 0 if has_x else (0 if equal else 1)",
            "    dm[0] = 1 if has_x else 0",
            "",
        ]

        # ── wide_cmp_lt: unsigned a < b ────────────────────────────────────────
        L += [
            "cdef inline void wide_cmp_lt(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n) noexcept nogil:",
            "    cdef int i, has_x = 0, j",
            "    for i in range(n):",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "    if has_x:",
            "        dv[0] = 0; dm[0] = 1",
            "        return",
            "    dv[0] = 0; dm[0] = 0",
            "    j = n - 1",
            "    while j >= 0:",
            "        if av[j] < bv[j]:",
            "            dv[0] = 1",
            "            return",
            "        if av[j] > bv[j]:",
            "            return",
            "        j -= 1",
            "",
        ]

        # ── wide_cmp_le: unsigned a <= b ───────────────────────────────────────
        L += [
            "cdef inline void wide_cmp_le(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n) noexcept nogil:",
            "    cdef int i, has_x = 0, j",
            "    for i in range(n):",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "    if has_x:",
            "        dv[0] = 0; dm[0] = 1",
            "        return",
            "    dv[0] = 1; dm[0] = 0",  # assume equal (≤ is True for equal)
            "    j = n - 1",
            "    while j >= 0:",
            "        if av[j] < bv[j]:",
            "            return",  # a < b → a <= b is True
            "        if av[j] > bv[j]:",
            "            dv[0] = 0",  # a > b → a <= b is False
            "            return",
            "        j -= 1",
            "",
        ]

        # ── wide_reduce_or ─────────────────────────────────────────────────────
        L += [
            "cdef inline void wide_reduce_or(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int n) noexcept nogil:",
            "    cdef int i, has_x = 0, any_one = 0",
            "    for i in range(n):",
            "        if av[i] & ~am[i]:",
            "            any_one = 1",
            "        if am[i] != 0:",
            "            has_x = 1",
            "    dv[0] = 1 if any_one else 0",
            "    dm[0] = 1 if (has_x and not any_one) else 0",
            "",
        ]

        # ── wide_reduce_and ────────────────────────────────────────────────────
        L += [
            "cdef inline void wide_reduce_and(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int n, int src_width) noexcept nogil:",
            "    cdef int i, has_x = 0, any_zero = 0, remaining_w",
            "    cdef unsigned long long tail_mask",
            "    for i in range(n):",
            "        remaining_w = src_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        if (~av[i] & ~am[i]) & tail_mask:",
            "            any_zero = 1",
            "        if am[i] & tail_mask:",
            "            has_x = 1",
            "    dv[0] = 0 if any_zero else (1 if not has_x else 0)",
            "    dm[0] = 1 if (has_x and not any_zero) else 0",
            "",
        ]

        # ── wide_reduce_xor ────────────────────────────────────────────────────
        L += [
            "cdef inline void wide_reduce_xor(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int n, int src_width) noexcept nogil:",
            "    cdef int i, bit_count = 0, has_x = 0, remaining_w",
            "    cdef unsigned long long word, tail_mask",
            "    for i in range(n):",
            "        remaining_w = src_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        if am[i] & tail_mask:",
            "            has_x = 1",
            "            break",
            "        word = av[i] & tail_mask",
            "        while word:",
            "            word &= word - 1",
            "            bit_count += 1",
            "    dv[0] = 0 if has_x else (bit_count & 1)",
            "    dm[0] = 1 if has_x else 0",
            "",
        ]

        # ── wide_mux ───────────────────────────────────────────────────────────
        # cond_v/cond_m are scalar 1-bit condition (val and mask plane).
        # When cond is X, result[i] = X where a[i]!=b[i] or either is X,
        # and the agreed definite value where a[i]==b[i] and both are known.
        L += [
            "cdef inline void wide_mux(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long cond_v, unsigned long long cond_m,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef int i, remaining_w",
            "    cdef unsigned long long tail_mask, agree_known",
            "    if cond_m != 0:",
            "        for i in range(n):",
            "            remaining_w = dst_width - i * 64",
            "            tail_mask = _word_mask64(remaining_w)",
            "            agree_known = ~am[i] & ~bm[i] & ~(av[i] ^ bv[i]) & tail_mask",
            "            dv[i] = av[i] & agree_known",
            "            dm[i] = tail_mask & ~agree_known",
            "    elif cond_v != 0:",
            "        wide_copy(dv, dm, av, am, n, dst_width)",
            "    else:",
            "        wide_copy(dv, dm, bv, bm, n, dst_width)",
            "",
        ]

        # ── wide_logical_truth: 1-bit bool result for if-condition evaluation ──
        L += [
            "cdef inline void wide_logical_truth(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int n) noexcept nogil:",
            "    cdef int i, any_one = 0, has_x = 0",
            "    for i in range(n):",
            "        if av[i] & ~am[i]:",
            "            any_one = 1",
            "        if am[i] != 0:",
            "            has_x = 1",
            "    dv[0] = 1 if any_one else 0",
            "    dm[0] = 0 if (any_one or not has_x) else 1",
            "",
        ]

        # ── wide_replicate ─────────────────────────────────────────────────────
        # Tiles element (elem_width bits from av/am) count times into dv/dm.
        # Non-overlapping tile OR: uses simple |= since tiles don't overlap.
        L += [
            "cdef inline void wide_replicate(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    int count, int elem_width, int n, int dst_width) noexcept nogil:",
            "    cdef int k, bit_off, wshift, bshift, wi, src_wi, remaining_w",
            "    cdef unsigned long long tail_mask, sv, sm, sv_prev, sm_prev",
            "    for wi in range(n):",
            "        dv[wi] = 0",
            "        dm[wi] = 0",
            "    for k in range(count):",
            "        bit_off = k * elem_width",
            "        wshift = bit_off >> 6",
            "        bshift = bit_off & 63",
            "        sv_prev = 0; sm_prev = 0",
            "        for wi in range(n):",
            "            src_wi = wi - wshift",
            "            if src_wi < 0:",
            "                sv = 0; sm = 0",
            "            else:",
            "                sv = av[src_wi]; sm = am[src_wi]",
            "            if bshift == 0:",
            "                dv[wi] |= sv",
            "                dm[wi] |= sm",
            "            else:",
            "                dv[wi] |= (sv << bshift) | (sv_prev >> (64 - bshift))",
            "                dm[wi] |= (sm << bshift) | (sm_prev >> (64 - bshift))",
            "            sv_prev = sv; sm_prev = sm",
            "    for wi in range(n):",
            "        remaining_w = dst_width - wi * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[wi] &= tail_mask",
            "        dm[wi] &= tail_mask",
            "",
        ]

        # ── Phase 3: multiply, divide, signed comparisons ──────────────────────

        # ── _mulhi64: upper 64 bits of 64×64 unsigned multiply ────────────────
        # Works without __int128; uses 32-bit limb decomposition.
        L += [
            "cdef inline unsigned long long _mulhi64(",
            "        unsigned long long a, unsigned long long b) noexcept nogil:",
            "    cdef unsigned long long MASK32 = <unsigned long long>0xFFFFFFFF",
            "    cdef unsigned long long a0 = a & MASK32, a1 = a >> 32",
            "    cdef unsigned long long b0 = b & MASK32, b1 = b >> 32",
            "    cdef unsigned long long p0 = a0 * b0, p1 = a1 * b0",
            "    cdef unsigned long long p2 = a0 * b1, p3 = a1 * b1",
            "    cdef unsigned long long m = (p0 >> 32) + (p1 & MASK32) + (p2 & MASK32)",
            "    return p3 + (p1 >> 32) + (p2 >> 32) + (m >> 32)",
            "",
        ]

        # ── wide_mul: grade-school n-word × n-word multiply ───────────────────
        # Accumulates partial products into a 16-word temp (max 1024-bit inputs).
        # Carry is propagated word-by-word; result is truncated to dst_width.
        # x/z: any mask bit in either operand → all-x result.
        L += [
            "cdef inline void wide_mul(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef unsigned long long tmp[16]",
            "    cdef int i, j, k, k2, remaining_w, has_x = 0",
            "    cdef unsigned long long lo, hi, old, tail_mask",
            "    for i in range(n):",
            "        dv[i] = 0",
            "        dm[i] = 0",
            "        tmp[i] = 0",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "    if has_x or n > 16:",
            "        for i in range(n):",
            "            remaining_w = dst_width - i * 64",
            "            tail_mask = _word_mask64(remaining_w)",
            "            dm[i] = tail_mask",
            "        return",
            "    for i in range(n):",
            "        for j in range(n):",
            "            k = i + j",
            "            if k >= n:",
            "                break",
            "            lo = av[i] * bv[j]",
            "            hi = _mulhi64(av[i], bv[j])",
            "            old = tmp[k]",
            "            tmp[k] = old + lo",
            "            if tmp[k] < old:",
            "                k2 = k + 1",
            "                while k2 < n:",
            "                    tmp[k2] += 1",
            "                    if tmp[k2] != 0:",
            "                        break",
            "                    k2 += 1",
            "            if k + 1 < n and hi != 0:",
            "                old = tmp[k + 1]",
            "                tmp[k + 1] = old + hi",
            "                if tmp[k + 1] < old:",
            "                    k2 = k + 2",
            "                    while k2 < n:",
            "                        tmp[k2] += 1",
            "                        if tmp[k2] != 0:",
            "                            break",
            "                        k2 += 1",
            "    for i in range(n):",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] = tmp[i] & tail_mask",
            "",
        ]

        # ── wide_div: restoring bit-by-bit unsigned division ──────────────────
        # Computes floor(A / B); division by zero yields x.
        # x/z in either operand also yields x.
        L += [
            "cdef inline void wide_div(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef unsigned long long Rv[16]",
            "    cdef int i, bit, wi, bs, ge, remaining_w, has_x = 0, b_zero = 1",
            "    cdef unsigned long long borrow, old, tail_mask",
            "    for i in range(n):",
            "        dv[i] = 0",
            "        dm[i] = 0",
            "        Rv[i] = 0",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "        if bv[i] != 0:",
            "            b_zero = 0",
            "    if has_x or b_zero or n > 16:",
            "        for i in range(n):",
            "            remaining_w = dst_width - i * 64",
            "            tail_mask = _word_mask64(remaining_w)",
            "            dm[i] = tail_mask",
            "        return",
            "    for bit in range(dst_width - 1, -1, -1):",
            "        wi = bit >> 6",
            "        bs = bit & 63",
            "        for i in range(n - 1, 0, -1):",
            "            Rv[i] = (Rv[i] << 1) | (Rv[i - 1] >> 63)",
            "        Rv[0] = (Rv[0] << 1) | ((av[wi] >> bs) & 1)",
            "        ge = 1",
            "        for i in range(n - 1, -1, -1):",
            "            if Rv[i] > bv[i]:",
            "                break",
            "            if Rv[i] < bv[i]:",
            "                ge = 0",
            "                break",
            "        if ge:",
            "            dv[wi] = dv[wi] | (<unsigned long long>1 << bs)",
            "            borrow = 0",
            "            for i in range(n):",
            "                old = Rv[i]",
            "                Rv[i] = old - bv[i] - borrow",
            "                if borrow:",
            "                    borrow = 1 if old <= bv[i] else 0",
            "                else:",
            "                    borrow = 1 if old < bv[i] else 0",
            "    for i in range(n):",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] &= tail_mask",
            "",
        ]

        # ── wide_mod: restoring bit-by-bit unsigned modulo ────────────────────
        # Computes A mod B; modulo by zero yields x.
        L += [
            "cdef inline void wide_mod(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int dst_width) noexcept nogil:",
            "    cdef unsigned long long Rv[16]",
            "    cdef int i, bit, wi, bs, ge, remaining_w, has_x = 0, b_zero = 1",
            "    cdef unsigned long long borrow, old, tail_mask",
            "    for i in range(n):",
            "        dv[i] = 0",
            "        dm[i] = 0",
            "        Rv[i] = 0",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "        if bv[i] != 0:",
            "            b_zero = 0",
            "    if has_x or b_zero or n > 16:",
            "        for i in range(n):",
            "            remaining_w = dst_width - i * 64",
            "            tail_mask = _word_mask64(remaining_w)",
            "            dm[i] = tail_mask",
            "        return",
            "    for bit in range(dst_width - 1, -1, -1):",
            "        wi = bit >> 6",
            "        bs = bit & 63",
            "        for i in range(n - 1, 0, -1):",
            "            Rv[i] = (Rv[i] << 1) | (Rv[i - 1] >> 63)",
            "        Rv[0] = (Rv[0] << 1) | ((av[wi] >> bs) & 1)",
            "        ge = 1",
            "        for i in range(n - 1, -1, -1):",
            "            if Rv[i] > bv[i]:",
            "                break",
            "            if Rv[i] < bv[i]:",
            "                ge = 0",
            "                break",
            "        if ge:",
            "            borrow = 0",
            "            for i in range(n):",
            "                old = Rv[i]",
            "                Rv[i] = old - bv[i] - borrow",
            "                if borrow:",
            "                    borrow = 1 if old <= bv[i] else 0",
            "                else:",
            "                    borrow = 1 if old < bv[i] else 0",
            "    for i in range(n):",
            "        remaining_w = dst_width - i * 64",
            "        tail_mask = _word_mask64(remaining_w)",
            "        dv[i] = Rv[i] & tail_mask",
            "",
        ]

        # ── wide_cmp_lt_signed: signed a < b ──────────────────────────────────
        # Sign bit at position src_width-1. Same-sign case reduces to unsigned cmp.
        L += [
            "cdef inline void wide_cmp_lt_signed(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int src_width) noexcept nogil:",
            "    cdef int i, has_x = 0, sign_word, sign_bit_idx, j",
            "    cdef unsigned long long a_sign, b_sign",
            "    for i in range(n):",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "    if has_x:",
            "        dv[0] = 0; dm[0] = 1",
            "        return",
            "    sign_word = (src_width - 1) >> 6",
            "    sign_bit_idx = (src_width - 1) & 63",
            "    a_sign = (av[sign_word] >> sign_bit_idx) & 1",
            "    b_sign = (bv[sign_word] >> sign_bit_idx) & 1",
            "    dv[0] = 0; dm[0] = 0",
            "    if a_sign != b_sign:",
            "        dv[0] = a_sign",
            "        return",
            "    j = n - 1",
            "    while j >= 0:",
            "        if av[j] < bv[j]:",
            "            dv[0] = 1",
            "            return",
            "        if av[j] > bv[j]:",
            "            return",
            "        j -= 1",
            "",
        ]

        # ── wide_cmp_le_signed: signed a <= b ─────────────────────────────────
        L += [
            "cdef inline void wide_cmp_le_signed(",
            "    unsigned long long *dv, unsigned long long *dm,",
            "    unsigned long long *av, unsigned long long *am,",
            "    unsigned long long *bv, unsigned long long *bm,",
            "    int n, int src_width) noexcept nogil:",
            "    cdef int i, has_x = 0, sign_word, sign_bit_idx, j",
            "    cdef unsigned long long a_sign, b_sign",
            "    for i in range(n):",
            "        if am[i] != 0 or bm[i] != 0:",
            "            has_x = 1",
            "    if has_x:",
            "        dv[0] = 0; dm[0] = 1",
            "        return",
            "    sign_word = (src_width - 1) >> 6",
            "    sign_bit_idx = (src_width - 1) & 63",
            "    a_sign = (av[sign_word] >> sign_bit_idx) & 1",
            "    b_sign = (bv[sign_word] >> sign_bit_idx) & 1",
            "    dv[0] = 1; dm[0] = 0",
            "    if a_sign != b_sign:",
            "        dv[0] = a_sign",
            "        return",
            "    j = n - 1",
            "    while j >= 0:",
            "        if av[j] < bv[j]:",
            "            return",
            "        if av[j] > bv[j]:",
            "            dv[0] = 0",
            "            return",
            "        j -= 1",
            "",
        ]

        return "\n".join(L)

    def _gen_wide_adapters(self) -> str:
        """Emit load/store adapter functions that bridge SimCtx ↔ scratch arrays.

        These functions ARE SimCtx-aware.  They use the existing wide_val/
        wide_mask/wide_nba_val/wide_nba_mask arrays and preserve all dirty-flag
        and NBA-staging semantics.  Emitted only when the module has wide state.
        """
        if not self._module_has_wide_state():
            return ""

        L: list[str] = [
            "# ── Wide load/store adapters ────────────────────────────────────────────────",
            "# Bridge between SimCtx signal storage and scratch word-array pairs.",
            "",
        ]

        # ── wide_load_signal ───────────────────────────────────────────────────
        L += [
            "cdef inline void wide_load_signal(",
            "    SimCtx *c, int sid,",
            "    unsigned long long *dv, unsigned long long *dm, int n) noexcept nogil:",
            "    cdef int i, words = c.wide_words[sid]",
            "    cdef int off = c.wide_offset[sid]",
            "    if words > 0:",
            "        for i in range(n):",
            "            if i < words:",
            "                dv[i] = c.wide_val[off + i]",
            "                dm[i] = c.wide_mask[off + i]",
            "            else:",
            "                dv[i] = 0",
            "                dm[i] = 0",
            "    else:",
            "        dv[0] = <unsigned long long>c.val[sid]",
            "        dm[0] = <unsigned long long>c.mask[sid]",
            "        for i in range(1, n):",
            "            dv[i] = 0",
            "            dm[i] = 0",
            "",
        ]

        # ── wide_store_signal ──────────────────────────────────────────────────
        # Blocking assign: write scratch → SimCtx, update dirty flag.
        # Mirrors val[sid]/mask[sid] from the low word of the wide array.
        L += [
            "cdef inline void wide_store_signal(",
            "    SimCtx *c, int sid,",
            "    unsigned long long *sv, unsigned long long *sm, int n) noexcept nogil:",
            "    cdef int i, words = c.wide_words[sid]",
            "    cdef int off = c.wide_offset[sid]",
            "    cdef int w = c.width[sid]",
            "    cdef unsigned long long tail_mask, sv_w, sm_w",
            "    cdef long long new_v, new_m",
            "    cdef int changed = 0",
            "    if words > 0:",
            "        for i in range(words):",
            "            tail_mask = _word_mask64(w - i * 64)",
            "            sv_w = sv[i] & tail_mask & ~sm[i]",
            "            sm_w = sm[i] & tail_mask",
            "            if sv_w != c.wide_val[off + i] or sm_w != c.wide_mask[off + i]:",
            "                c.wide_val[off + i] = sv_w",
            "                c.wide_mask[off + i] = sm_w",
            "                changed = 1",
            "        new_v = <long long>c.wide_val[off]",
            "        new_m = <long long>c.wide_mask[off]",
            "    else:",
            "        new_v = <long long>(sv[0] & <unsigned long long>wmask(w) & ~sm[0])",
            "        new_m = <long long>(sm[0] & <unsigned long long>wmask(w))",
            "    if new_v != c.val[sid] or new_m != c.mask[sid]:",
            "        c.val[sid] = new_v",
            "        c.mask[sid] = new_m",
            "        changed = 1",
            "    if changed:",
            "        c.dirty[sid] = 1",
            "",
        ]

        # ── wide_stage_signal ──────────────────────────────────────────────────
        # Non-blocking assign: write scratch → NBA staging buffers.
        L += [
            "cdef inline void wide_stage_signal(",
            "    SimCtx *c, int sid,",
            "    unsigned long long *sv, unsigned long long *sm, int n) noexcept nogil:",
            "    cdef int i, words = c.wide_words[sid]",
            "    cdef int off = c.wide_offset[sid]",
            "    cdef int w = c.width[sid]",
            "    cdef unsigned long long tail_mask",
            "    if words > 0:",
            "        for i in range(words):",
            "            tail_mask = _word_mask64(w - i * 64)",
            "            c.wide_nba_val[off + i]  = sv[i] & tail_mask & ~sm[i]",
            "            c.wide_nba_mask[off + i] = sm[i] & tail_mask",
            "        c.nba_val[sid]  = <long long>c.wide_nba_val[off]",
            "        c.nba_mask[sid] = <long long>c.wide_nba_mask[off]",
            "    else:",
            "        c.nba_val[sid]  = <long long>(sv[0] & <unsigned long long>wmask(w) & ~sm[0])",
            "        c.nba_mask[sid] = <long long>(sm[0] & <unsigned long long>wmask(w))",
            "    c.nba_dirty[sid] = 1",
            "    c.nba_pending   = 1",
            "",
        ]

        return "\n".join(L)

    def _gen_wide_mem_helpers(self) -> str:
        lines: list[str] = []
        for mid in range(self._n_mems):
            elem_width, _depth = self._mem_info[mid]
            if elem_width <= _WORD_BITS:
                continue
            words = self._mem_words(mid)
            lines.extend(
                [
                    f"cdef inline unsigned long long _wmem{mid}_word_val(SimCtx *c, int addr, int word_index) noexcept nogil:",
                    f"    if 0 <= word_index < {words}:",
                    f"        return c.wide_mem_{mid}_val[addr * {words} + word_index]",
                    "    return 0",
                    "",
                    f"cdef inline unsigned long long _wmem{mid}_word_mask(SimCtx *c, int addr, int word_index) noexcept nogil:",
                    f"    if 0 <= word_index < {words}:",
                    f"        return c.wide_mem_{mid}_mask[addr * {words} + word_index]",
                    "    return 0",
                    "",
                    f"cdef inline unsigned long long _wmem{mid}_extract_val(SimCtx *c, int addr, int lsb) noexcept nogil:",
                    "    cdef int src_word = lsb >> 6",
                    "    cdef int src_shift = lsb & 63",
                    f"    cdef unsigned long long lo_v = _wmem{mid}_word_val(c, addr, src_word)",
                    "    cdef unsigned long long hi_v",
                    "    if src_shift == 0:",
                    "        return lo_v",
                    f"    hi_v = _wmem{mid}_word_val(c, addr, src_word + 1)",
                    "    return (lo_v >> src_shift) | (hi_v << (64 - src_shift))",
                    "",
                    f"cdef inline unsigned long long _wmem{mid}_extract_mask(SimCtx *c, int addr, int lsb) noexcept nogil:",
                    "    cdef int src_word = lsb >> 6",
                    "    cdef int src_shift = lsb & 63",
                    f"    cdef unsigned long long lo_m = _wmem{mid}_word_mask(c, addr, src_word)",
                    "    cdef unsigned long long hi_m",
                    "    if src_shift == 0:",
                    "        return lo_m",
                    f"    hi_m = _wmem{mid}_word_mask(c, addr, src_word + 1)",
                    "    return (lo_m >> src_shift) | (hi_m << (64 - src_shift))",
                    "",
                    f"cdef inline object _wmem{mid}_py_extract_val(SimCtx *c, int addr, int lsb, int width):",
                    "    cdef int i, chunk_lsb, chunk_w",
                    "    cdef object value = 0",
                    "    cdef unsigned long long word_val",
                    "    for i in range(((width + 63) >> 6) - 1, -1, -1):",
                    "        chunk_lsb = lsb + (i * 64)",
                    "        chunk_w = width - (i * 64)",
                    "        if chunk_w > 64:",
                    "            chunk_w = 64",
                    f"        word_val = _wmem{mid}_extract_val(c, addr, chunk_lsb) & _word_mask64(chunk_w)",
                    "        value = (value << chunk_w) | word_val",
                    "    return value & ((((<object>1) << width) - 1))",
                    "",
                    f"cdef inline object _wmem{mid}_py_extract_mask(SimCtx *c, int addr, int lsb, int width):",
                    "    cdef int i, chunk_lsb, chunk_w",
                    "    cdef object value = 0",
                    "    cdef unsigned long long word_mask",
                    "    for i in range(((width + 63) >> 6) - 1, -1, -1):",
                    "        chunk_lsb = lsb + (i * 64)",
                    "        chunk_w = width - (i * 64)",
                    "        if chunk_w > 64:",
                    "            chunk_w = 64",
                    f"        word_mask = _wmem{mid}_extract_mask(c, addr, chunk_lsb) & _word_mask64(chunk_w)",
                    "        value = (value << chunk_w) | word_mask",
                    "    return value & ((((<object>1) << width) - 1))",
                    "",
                    f"cdef inline void _wmem{mid}_stage_insert_signal_slice(SimCtx *c, int addr, int dst_lsb, int src_sid, int src_lsb, int src_width) noexcept nogil:",
                    "    cdef int start_word, end_word, word_index",
                    "    cdef int chunk_lsb, chunk_msb, chunk_w, src_shift, word_lsb",
                    "    cdef unsigned long long chunk_mask, chunk_val, chunk_rmask",
                    "    if src_width <= 0:",
                    "        return",
                    "    start_word = dst_lsb >> 6",
                    "    end_word = (dst_lsb + src_width - 1) >> 6",
                    "    for word_index in range(start_word, end_word + 1):",
                    "        chunk_lsb = dst_lsb if dst_lsb > word_index * 64 else word_index * 64",
                    "        chunk_msb = dst_lsb + src_width - 1",
                    "        if chunk_msb > ((word_index + 1) * 64) - 1:",
                    "            chunk_msb = ((word_index + 1) * 64) - 1",
                    "        chunk_w = chunk_msb - chunk_lsb + 1",
                    "        src_shift = chunk_lsb - dst_lsb",
                    "        word_lsb = chunk_lsb - (word_index * 64)",
                    "        chunk_mask = _word_mask64(chunk_w)",
                    "        chunk_val = _sig_extract_word_val(c, src_sid, src_lsb + src_shift) & chunk_mask",
                    "        chunk_rmask = _sig_extract_word_mask(c, src_sid, src_lsb + src_shift) & chunk_mask",
                    f"        c.nba_mem_range_mid[c.nba_mem_range_count] = {mid}",
                    f"        c.nba_mem_range_addr[c.nba_mem_range_count] = (addr * {words}) + word_index",
                    "        c.nba_mem_range_msb[c.nba_mem_range_count] = word_lsb + chunk_w - 1",
                    "        c.nba_mem_range_lsb[c.nba_mem_range_count] = word_lsb",
                    "        c.nba_mem_range_val[c.nba_mem_range_count] = <long long>chunk_val",
                    "        c.nba_mem_range_mask[c.nba_mem_range_count] = <long long>chunk_rmask",
                    "        c.nba_mem_range_count += 1",
                    "    c.nba_pending = 1",
                    "",
                    f"cdef inline void _wmem{mid}_assign_insert_signal_slice(SimCtx *c, int addr, int dst_lsb, int src_sid, int src_lsb, int src_width, int marker_sid) noexcept nogil:",
                    "    cdef int start_word, end_word, word_index",
                    "    cdef int chunk_lsb, chunk_msb, chunk_w, src_shift, word_lsb",
                    "    cdef int word_addr",
                    "    cdef int changed = 0",
                    "    cdef unsigned long long chunk_mask, word_mask, chunk_val, chunk_rmask, new_val, new_mask",
                    "    if src_width <= 0:",
                    "        return",
                    "    start_word = dst_lsb >> 6",
                    "    end_word = (dst_lsb + src_width - 1) >> 6",
                    "    for word_index in range(start_word, end_word + 1):",
                    "        chunk_lsb = dst_lsb if dst_lsb > word_index * 64 else word_index * 64",
                    "        chunk_msb = dst_lsb + src_width - 1",
                    "        if chunk_msb > ((word_index + 1) * 64) - 1:",
                    "            chunk_msb = ((word_index + 1) * 64) - 1",
                    "        chunk_w = chunk_msb - chunk_lsb + 1",
                    "        src_shift = chunk_lsb - dst_lsb",
                    "        word_lsb = chunk_lsb - (word_index * 64)",
                    f"        word_addr = (addr * {words}) + word_index",
                    "        chunk_mask = _word_mask64(chunk_w)",
                    "        word_mask = chunk_mask << word_lsb",
                    "        chunk_val = _sig_extract_word_val(c, src_sid, src_lsb + src_shift) & chunk_mask",
                    "        chunk_rmask = _sig_extract_word_mask(c, src_sid, src_lsb + src_shift) & chunk_mask",
                    f"        new_val = ((c.wide_mem_{mid}_val[word_addr] & ~word_mask) | (((chunk_val & ~chunk_rmask) & chunk_mask) << word_lsb))",
                    f"        new_mask = ((c.wide_mem_{mid}_mask[word_addr] & ~word_mask) | ((chunk_rmask & chunk_mask) << word_lsb))",
                    f"        if c.wide_mem_{mid}_val[word_addr] != new_val or c.wide_mem_{mid}_mask[word_addr] != new_mask:",
                    f"            c.wide_mem_{mid}_val[word_addr] = new_val",
                    f"            c.wide_mem_{mid}_mask[word_addr] = new_mask",
                    "            changed = 1",
                    "    if changed:",
                    "        c.val[marker_sid] ^= 1",
                    "        c.dirty[marker_sid] = 1",
                    "",
                    f"cdef inline void wide_load_wmem{mid}(",
                    "    SimCtx *c, int addr,",
                    "    unsigned long long *dv, unsigned long long *dm, int n) noexcept nogil:",
                    "    cdef int i",
                    "    for i in range(n):",
                    f"        if i < {words}:",
                    f"            dv[i] = c.wide_mem_{mid}_val[addr * {words} + i]",
                    f"            dm[i] = c.wide_mem_{mid}_mask[addr * {words} + i]",
                    "        else:",
                    "            dv[i] = 0",
                    "            dm[i] = 0",
                    "",
                ]
            )
        return "\n".join(lines)
