"""User-defined `function` call differential fuzzing (work plan item 3.4,
Phase 6).

Every earlier phase (1-5, see `test_differential.py`/`test_differential_
statements.py`) generates only `$signed`/`$unsigned` as "calls" in an
expression tree -- real Verilog `function`s (declared once, called from
many expression positions; the standard way real RTL factors out reusable
combinational logic, e.g. parity/priority-encode/saturate helpers) have
never been generated by either fuzzer, despite all four engines already
correctly IMPLEMENTING user-defined function calls
(`sim/evaluator.py:_eval_user_function`, `sim/vm/compiler.py:
_compile_user_function`, `sim/compiled/_expr_emitter.py:_emit_func_call`)
-- only deterministic, hand-written coverage exists today
(`tests/test_sim/test_function_task.py`).

**Why this is its own file, not a `test_differential.py`/`test_
differential_statements.py` addition**: both of those fuzzers assign every
generated case to a fixed 96-bit destination (`y_comb_N`/`y_ff_N`/
`y_stmt_N`) regardless of the case's own content. The compiled engine
cannot yet handle a `FunctionCall` node ANYWHERE in an RHS tree feeding a
destination wider than 64 bits -- confirmed directly: it raises
`NotImplementedError` (`_process_compiler.py`'s "RHS shape not yet
supported for a destination wider than 64 bits" guard; neither
`_wide_emitter.py`'s recursive scratch emitter nor its Python-bignum
fallback has ever supported `FunctionCall`). Plugging function-call
generation into either fuzzer's shared 96-bit-destination harness would
make ANY `VERIFORGE_DIFF_COMPILED=1` run crash outright (not just fail an
assertion) the moment a single case happened to contain a call anywhere in
its randomly generated tree. This is the exact same constraint that
already excluded `**` from both fuzzers in favor of its own dedicated,
narrower-destination `test_power_operator.py` (see that file's own
docstring) -- and, unlike `**` (which is also broken on `vm-fast` for wide
operands), function calls work correctly on `vm`/`vm-fast`/`reference` at
any width; only `compiled`'s DESTINATION width is the constraint, so a
plain differential fuzzer (not a hand-written regression file) is still
the right tool here, just with a narrower (64-bit, not 96-bit) uniform
destination that stays inside compiled's supported range. Confirmed
directly (scratch probes, not just reasoning) that a function call nested
arbitrarily deep inside a larger expression works correctly across all
four engines as long as the OUTER destination stays <=64 bits.

**Design**: reuses `test_differential.py`'s own `_gen_expr`/`_gen_leaf`
(via its `callables` parameter, itself a no-op for that file's own use --
see its docstring) and fixed 8-signal input set unchanged, passing
`FIXED_FUNCTIONS` (also defined in `test_differential.py`, so both files
share one canonical function pool + declaration-text generator) so a
"call" node can appear at any eligible recursion point, nested inside
further binary/unary/ternary/etc. composition exactly like any other node
kind -- exercising argument-expression width/signedness propagation INTO
a real call site and the call's own return value propagating back OUT,
the one call shape (`$signed`/`$unsigned`) fuzzed so far can't stand in
for. `FIXED_FUNCTIONS`' bodies are fixed and non-recursive (see that
list's own docstring in `test_differential.py` for why) -- this phase
fuzzes CALL SITES, not the space of possible function bodies.

Determinism: `VERIFORGE_DIFF_FUNC_SEED` (default 20260701) seeds the
generator; `VERIFORGE_DIFF_FUNC_CASES` (default 150) sets how many random
expressions are generated, batched the same way as `test_differential.py`.
`VERIFORGE_DIFF_FUNC_COMPILED=1` opts the compiled engine in, same as both
earlier fuzzers and for the same reason (per-module Cython compilation is
too slow for the default run's "a few seconds" budget).
"""

from __future__ import annotations

import os
import random

import pytest

from . import test_differential as td
from .engines import ENGINES

# =====================================================================
# Configuration
# =====================================================================

_SEED = int(os.environ.get("VERIFORGE_DIFF_FUNC_SEED", "20260701"))
_NUM_CASES = int(os.environ.get("VERIFORGE_DIFF_FUNC_CASES", "150"))
_COMPILED_ENABLED = os.environ.get("VERIFORGE_DIFF_FUNC_COMPILED") == "1"
_BATCH_SIZE = 10
_MAX_DEPTH = 4
_DEST_WIDTH = 64
"""Narrower than `test_differential.py`'s 96 bits -- deliberately: see this
file's module docstring for why the destination must stay <=64 bits for
the compiled engine to support a `FunctionCall` anywhere in the RHS tree."""

# =====================================================================
# Random expression generation (function calls via td._gen_expr's
# callables parameter)
# =====================================================================


def _generate_cases(seed: int, n: int) -> list[td._Case]:
    rng = random.Random(seed)
    return [td._Case(i, td._gen_expr(rng, _MAX_DEPTH, (), td.FIXED_FUNCTIONS)) for i in range(n)]


def _batches(cases: list[td._Case]) -> list[list[td._Case]]:
    return [cases[i : i + _BATCH_SIZE] for i in range(0, len(cases), _BATCH_SIZE)]


_CASES = _generate_cases(_SEED, _NUM_CASES)
_BATCHES = _batches(_CASES)

# =====================================================================
# Verilog module generation
# =====================================================================


def _build_batch_module(cases: list[td._Case]) -> str:
    ports = ["input clk"]
    for name, width, signed in td.FIXED_SIGNALS:
        sig = "signed " if signed else ""
        ports.append(f"input {sig}[{width - 1}:0] {name}")
    for c in cases:
        ports.append(f"output [{_DEST_WIDTH - 1}:0] y_comb_{c.idx}")
        ports.append(f"output reg [{_DEST_WIDTH - 1}:0] y_ff_{c.idx}")
    header = ",\n    ".join(ports)
    func_decls = "\n".join(td._func_declaration(spec) for spec in td.FIXED_FUNCTIONS)
    assigns = "\n".join(f"    assign y_comb_{c.idx} = {c.expr};" for c in cases)
    nba = "\n".join(f"        y_ff_{c.idx} <= {c.expr};" for c in cases)
    return (
        f"module t(\n    {header}\n);\n{func_decls}\n{assigns}\n"
        f"    always @(posedge clk) begin\n{nba}\n    end\nendmodule\n"
    )


# =====================================================================
# Simulation plumbing (same pattern as test_differential.py)
# =====================================================================


def _run_batch(
    source: str, engine: str, cases: list[td._Case], vectors: list[dict[str, td.Value]]
) -> list[tuple[dict[int, td.Value], dict[int, td.Value]]]:
    sim = td._sim_for(source, engine)
    sim.drive("clk", td.Value(0, width=1))
    for name, width, _signed in td.FIXED_SIGNALS:
        sim.drive(name, td.Value(0, width=width))
    sim.settle()

    results: list[tuple[dict[int, td.Value], dict[int, td.Value]]] = []
    for vec in vectors:
        for name, value in vec.items():
            sim.drive(name, value)
        sim.settle()
        comb = {c.idx: sim.read(f"y_comb_{c.idx}") for c in cases}
        sim.drive("clk", td.Value(1, width=1))
        sim.settle()
        sim.drive("clk", td.Value(0, width=1))
        sim.settle()
        ff = {c.idx: sim.read(f"y_ff_{c.idx}") for c in cases}
        results.append((comb, ff))
    return results


# =====================================================================
# Test
# =====================================================================


@pytest.mark.cross_engine
@pytest.mark.parametrize("batch_idx", range(len(_BATCHES)))
def test_differential_functions(batch_idx: int) -> None:
    cases = _BATCHES[batch_idx]
    source = _build_batch_module(cases)
    vectors = td._gen_vectors(f"{_SEED}:func_vectors:{batch_idx}")

    oracle = _run_batch(source, "reference", cases, vectors)
    engines = [e for e in ENGINES if e != "reference" and (e != "compiled" or _COMPILED_ENABLED)]
    for engine in engines:
        got = _run_batch(source, engine, cases, vectors)
        for vec_idx, ((exp_comb, exp_ff), (got_comb, got_ff)) in enumerate(zip(oracle, got, strict=True)):
            for c in cases:
                exp_c, got_c = exp_comb[c.idx], got_comb[c.idx]
                assert exp_c == got_c, (
                    f"differential mismatch: engine={engine} seed={_SEED} batch={batch_idx} "
                    f"case={c.idx} vector={vec_idx} signal=y_comb_{c.idx}\n"
                    f"expr: {c.expr}\n"
                    f"vector: {vectors[vec_idx]}\n"
                    f"expected(reference)={exp_c!r} got({engine})={got_c!r}\n"
                    f"module source:\n{source}"
                )
                exp_f, got_f = exp_ff[c.idx], got_ff[c.idx]
                assert exp_f == got_f, (
                    f"differential mismatch: engine={engine} seed={_SEED} batch={batch_idx} "
                    f"case={c.idx} vector={vec_idx} signal=y_ff_{c.idx}\n"
                    f"expr: {c.expr}\n"
                    f"vector: {vectors[vec_idx]}\n"
                    f"expected(reference)={exp_f!r} got({engine})={got_f!r}\n"
                    f"module source:\n{source}"
                )
