"""User-defined `function` call differential fuzzing (work plan item 3.4,
Phase 6).

Every earlier phase (1-5, see `test_differential.py`/`test_differential_
statements.py`) generates only `$signed`/`$unsigned` as "calls" in an
expression tree -- real Verilog `function`s (declared once, called from
many expression positions; the standard way real RTL factors out reusable
combinational logic, e.g. parity/priority-encode/saturate helpers) have
never been generated by either fuzzer, despite all four engines already
correctly IMPLEMENTING user-defined function calls
(`sim/evaluator.py:_eval_user_function`, `sim/vm/compiler.py:
_compile_user_function`, `sim/compiled/_expr_emitter.py:_emit_func_call`)
-- only deterministic, hand-written coverage exists today
(`tests/test_sim/test_function_task.py`).

**Why this is its own file, not a `test_differential.py`/`test_
differential_statements.py` addition**: both of those fuzzers assign every
generated case to a fixed 96-bit destination (`y_comb_N`/`y_ff_N`/
`y_stmt_N`) regardless of the case's own content. The compiled engine
cannot yet handle a `FunctionCall` node ANYWHERE in an RHS tree feeding a
destination wider than 64 bits -- confirmed directly: it raises
`NotImplementedError` (`_process_compiler.py`'s "RHS shape not yet
supported for a destination wider than 64 bits" guard; neither
`_wide_emitter.py`'s recursive scratch emitter nor its Python-bignum
fallback has ever supported `FunctionCall`). Plugging function-call
generation into either fuzzer's shared 96-bit-destination harness would
make ANY `VERIFORGE_DIFF_COMPILED=1` run crash outright (not just fail an
assertion) the moment a single case happened to contain a call anywhere in
its randomly generated tree. This is the exact same constraint that
already excluded `**` from both fuzzers in favor of its own dedicated,
narrower-destination `test_power_operator.py` (see that file's own
docstring) -- and, unlike `**` (which is also broken on `vm-fast` for wide
operands), function calls work correctly on `vm`/`vm-fast`/`reference` at
any width; only `compiled`'s DESTINATION width is the constraint, so a
plain differential fuzzer (not a hand-written regression file) is still
the right tool here, just with a narrower (64-bit, not 96-bit) uniform
destination that stays inside compiled's supported range. Confirmed
directly (scratch probes, not just reasoning) that a function call nested
arbitrarily deep inside a larger expression works correctly across all
four engines as long as the OUTER destination stays <=64 bits.

**Design**: reuses `test_differential.py`'s own `_gen_expr`/`_gen_leaf`
(via its `callables` parameter, itself a no-op for that file's own use --
see its docstring) and fixed 8-signal input set unchanged, passing
`FIXED_FUNCTIONS` (also defined in `test_differential.py`, so both files
share one canonical function pool + declaration-text generator) so a
"call" node can appear at any eligible recursion point, nested inside
further binary/unary/ternary/etc. composition exactly like any other node
kind -- exercising argument-expression width/signedness propagation INTO
a real call site and the call's own return value propagating back OUT,
the one call shape (`$signed`/`$unsigned`) fuzzed so far can't stand in
for. `FIXED_FUNCTIONS`' bodies are fixed and non-recursive (see that
list's own docstring in `test_differential.py` for why) -- this phase
fuzzes CALL SITES, not the space of possible function bodies.

Determinism: `VERIFORGE_DIFF_FUNC_SEED` (default 20260701) seeds the
generator; `VERIFORGE_DIFF_FUNC_CASES` (default 150) sets how many random
expressions are generated, batched the same way as `test_differential.py`.
`VERIFORGE_DIFF_FUNC_COMPILED=1` opts the compiled engine in, same as both
earlier fuzzers and for the same reason (per-module Cython compilation is
too slow for the default run's "a few seconds" budget).
"""

from __future__ import annotations

import os
import random

import pytest

from . import test_differential as td
from .engines import ENGINES

# =====================================================================
# Configuration
# =====================================================================

_SEED = int(os.environ.get("VERIFORGE_DIFF_FUNC_SEED", "20260701"))
_NUM_CASES = int(os.environ.get("VERIFORGE_DIFF_FUNC_CASES", "150"))
_COMPILED_ENABLED = os.environ.get("VERIFORGE_DIFF_FUNC_COMPILED") == "1"
_BATCH_SIZE = 10
_MAX_DEPTH = 4
_DEST_WIDTH = 64
"""Narrower than `test_differential.py`'s 96 bits -- deliberately: see this
file's module docstring for why the destination must stay <=64 bits for
the compiled engine to support a `FunctionCall` anywhere in the RHS tree."""

# =====================================================================
# Random expression generation (function calls via td._gen_expr's
# callables parameter)
# =====================================================================


def _generate_cases(seed: int, n: int) -> list[td._Case]:
    rng = random.Random(seed)
    return [td._Case(i, td._gen_expr(rng, _MAX_DEPTH, (), td.FIXED_FUNCTIONS)) for i in range(n)]


def _batches(cases: list[td._Case]) -> list[list[td._Case]]:
    return [cases[i : i + _BATCH_SIZE] for i in range(0, len(cases), _BATCH_SIZE)]


_CASES = _generate_cases(_SEED, _NUM_CASES)
_BATCHES = _batches(_CASES)

# =====================================================================
# Verilog module generation
# =====================================================================


def _build_batch_module(cases: list[td._Case]) -> str:
    ports = ["input clk"]
    for name, width, signed in td.FIXED_SIGNALS:
        sig = "signed " if signed else ""
        ports.append(f"input {sig}[{width - 1}:0] {name}")
    for c in cases:
        ports.append(f"output [{_DEST_WIDTH - 1}:0] y_comb_{c.idx}")
        ports.append(f"output reg [{_DEST_WIDTH - 1}:0] y_ff_{c.idx}")
    header = ",\n    ".join(ports)
    func_decls = "\n".join(td._func_declaration(spec) for spec in td.FIXED_FUNCTIONS)
    assigns = "\n".join(f"    assign y_comb_{c.idx} = {c.expr};" for c in cases)
    nba = "\n".join(f"        y_ff_{c.idx} <= {c.expr};" for c in cases)
    return (
        f"module t(\n    {header}\n);\n{func_decls}\n{assigns}\n"
        f"    always @(posedge clk) begin\n{nba}\n    end\nendmodule\n"
    )


# =====================================================================
# Simulation plumbing (same pattern as test_differential.py)
# =====================================================================


def _run_batch(
    source: str, engine: str, cases: list[td._Case], vectors: list[dict[str, td.Value]]
) -> list[tuple[dict[int, td.Value], dict[int, td.Value]]]:
    sim = td._sim_for(source, engine)
    sim.drive("clk", td.Value(0, width=1))
    for name, width, _signed in td.FIXED_SIGNALS:
        sim.drive(name, td.Value(0, width=width))
    sim.settle()

    results: list[tuple[dict[int, td.Value], dict[int, td.Value]]] = []
    for vec in vectors:
        for name, value in vec.items():
            sim.drive(name, value)
        sim.settle()
        comb = {c.idx: sim.read(f"y_comb_{c.idx}") for c in cases}
        sim.drive("clk", td.Value(1, width=1))
        sim.settle()
        sim.drive("clk", td.Value(0, width=1))
        sim.settle()
        ff = {c.idx: sim.read(f"y_ff_{c.idx}") for c in cases}
        results.append((comb, ff))
    return results


# =====================================================================
# Test
# =====================================================================


@pytest.mark.cross_engine
@pytest.mark.parametrize("batch_idx", range(len(_BATCHES)))
def test_differential_functions(batch_idx: int) -> None:
    cases = _BATCHES[batch_idx]
    source = _build_batch_module(cases)
    vectors = td._gen_vectors(f"{_SEED}:func_vectors:{batch_idx}")

    oracle = _run_batch(source, "reference", cases, vectors)
    engines = [e for e in ENGINES if e != "reference" and (e != "compiled" or _COMPILED_ENABLED)]
    for engine in engines:
        got = _run_batch(source, engine, cases, vectors)
        for vec_idx, ((exp_comb, exp_ff), (got_comb, got_ff)) in enumerate(zip(oracle, got, strict=True)):
            for c in cases:
                exp_c, got_c = exp_comb[c.idx], got_comb[c.idx]
                assert exp_c == got_c, (
                    f"differential mismatch: engine={engine} seed={_SEED} batch={batch_idx} "
                    f"case={c.idx} vector={vec_idx} signal=y_comb_{c.idx}\n"
                    f"expr: {c.expr}\n"
                    f"vector: {vectors[vec_idx]}\n"
                    f"expected(reference)={exp_c!r} got({engine})={got_c!r}\n"
                    f"module source:\n{source}"
                )
                exp_f, got_f = exp_ff[c.idx], got_ff[c.idx]
                assert exp_f == got_f, (
                    f"differential mismatch: engine={engine} seed={_SEED} batch={batch_idx} "
                    f"case={c.idx} vector={vec_idx} signal=y_ff_{c.idx}\n"
                    f"expr: {c.expr}\n"
                    f"vector: {vectors[vec_idx]}\n"
                    f"expected(reference)={exp_f!r} got({engine})={got_f!r}\n"
                    f"module source:\n{source}"
                )


@pytest.mark.cross_engine
def test_reduction_of_wide_unary_minus_function_argument() -> None:
    """Regression test for a confirmed compiled-engine bug: a reduction
    over a wide (>64-bit) unary-`-` operand, passed as a function-call
    argument, silently dropped the operand's high bit.

    Root cause: the destination (`y0`, 64 bits) is narrow, but `a5`
    (65 bits) negated inside a reduction needs 65 bits internally,
    routing the WHOLE statement through `_wide_emitter.py`'s recursive
    `_emit_wide_lhs_write_new` -> `_emit_wide_expr_to_scratch`. That
    path recurses into the NARROW emitter for each function-call
    argument (`_emit_user_func_call_expr`), and the reduction argument's
    own attempt to hoist its wide sub-computation
    (`_emit_wide_reduction_to_value`, in `_expr_emitter.py`) requires an
    active `_et_pending` list to append to -- which `_emit_wide_lhs_
    write_new` never opened, unlike every other top-level-statement
    compiler that can reach the narrow emitter. Silently fell back to
    the native-`long long`-only reduction formula, which only sees a5's
    low 64 bits. Confirmed against Icarus (cross-engine): reference/
    vm/vm-fast all agree; only compiled disagreed before the fix.
    """
    source = """
module t(
    input clk,
    input signed [0:0] a0,
    input [7:0] a1,
    input signed [15:0] a2,
    input [62:0] a3,
    input signed [63:0] a4,
    input [64:0] a5,
    input signed [79:0] a6,
    input [0:0] a7,
    output [63:0] y0
);
    function [62:0] fn_sel1(input [0:0] a, input [62:0] b);
        begin
            fn_sel1 = a ? b : ~b;
        end
    endfunction
    assign y0 = fn_sel1({2{((~|a6[62]) && {a7, a6[5]})}}, (^(-a5)));
endmodule
"""
    values = {
        "a0": td.Value(1, width=1),
        "a1": td.Value(4, width=8),
        "a2": td.Value(56033, width=16),
        "a3": td.Value(6082846213464634453, width=63),
        "a4": td.Value(11875740104559844210, width=64),
        "a5": td.Value(31503097247306016283, width=65),
        "a6": td.Value(742502492484475909464865, width=80),
        "a7": td.Value(0, width=1),
    }
    ref_val = None
    for engine in ENGINES:
        sim = td._sim_for(source, engine)
        sim.drive("clk", td.Value(0, width=1))
        for name, width, _signed in td.FIXED_SIGNALS:
            sim.drive(name, td.Value(0, width=width))
        sim.settle()
        for name, value in values.items():
            sim.drive(name, value)
        sim.settle()
        got = sim.read("y0")
        if ref_val is None:
            ref_val = got
        assert got == ref_val, f"engine={engine} got={got!r} expected={ref_val!r}"


@pytest.mark.cross_engine
def test_computed_wide_function_argument_from_narrow_signals() -> None:
    """Regression test for a confirmed compiled-engine bug:
    `_rhs_needs_wide_eval` (`sim/compiled/_wide_emitter.py`) -- the gate
    deciding whether a narrow-destination statement even ATTEMPTS wide-
    path evaluation -- never detected a function-call argument that is
    itself a COMPUTED wide value (a concatenation of individually narrow
    pieces whose combined width exceeds 64 bits), only an individually
    wide SIGNAL reference anywhere in the tree (`_expr_uses_wide_signal`,
    the old catch-all).

    The outer `&&` is what actually trips the old bug: `_rhs_needs_wide_
    eval`'s old `&&`/`||` branch UNCONDITIONALLY returned `max(_expr_
    width(left), _expr_width(right)) > _WORD_BITS` -- both operands here
    are self-determined-1-bit-ish (a reduction, and a 3-bit replication
    of a reduction), so that comparison is always small and the branch
    returns `False` immediately, without ever falling through to the
    `_expr_uses_wide_signal` catch-all that would otherwise have found
    `a5`/`a6` nested deep inside (as `fn_add8`'s `{a4, a6, a7}`/
    `$unsigned(a5)` arguments, and `$unsigned(a5[47:37])`). Wide-path
    evaluation never triggers, so the pure-narrow fallback computes
    `fn_add8`'s wide arguments and the reduction over them using only
    their low 64 bits, silently losing precision needed for the `~&`
    reduction's own x-propagation. `_expr_max_internal_width` recurses
    through the WHOLE tree regardless of the top-level operator, so it
    isn't fooled by an outer op whose own self-determined width happens
    to be small. Confirmed against Icarus (cross-engine): reference/vm/
    vm-fast all agree (mask=0x1); only compiled disagreed before the fix
    (mask=0x7, spuriously marking bits 1-2 as ambiguous).
    """
    source = """
module t(
    input clk,
    input signed [0:0] a0,
    input [7:0] a1,
    input signed [15:0] a2,
    input [62:0] a3,
    input signed [63:0] a4,
    input [64:0] a5,
    input signed [79:0] a6,
    input [0:0] a7,
    output [63:0] y0
);
    function [7:0] fn_add8(input [7:0] a, input [7:0] b);
        begin
            fn_add8 = a + b;
        end
    endfunction
    assign y0 = ((~&fn_add8({a4, a6, a7}, $unsigned(a5))) && {3{(~^$unsigned(a5[47:37]))}});
endmodule
"""
    values = {
        "a0": td.Value(0, width=1),
        "a1": td.Value(132, width=8),
        "a2": td.Value(11873, width=16),
        "a3": td.Value(9109546452988579173, width=63),
        "a4": td.Value(4948743542175063856, width=64),
        "a5": td.Value(0, width=65, mask=0x1FFFFFFFFFFFFFFFF),
        "a6": td.Value(124888234732848633443292, width=80),
        "a7": td.Value(0, width=1),
    }
    ref_val = None
    for engine in ENGINES:
        sim = td._sim_for(source, engine)
        sim.drive("clk", td.Value(0, width=1))
        for name, width, _signed in td.FIXED_SIGNALS:
            sim.drive(name, td.Value(0, width=width))
        sim.settle()
        for name, value in values.items():
            sim.drive(name, value)
        sim.settle()
        got = sim.read("y0")
        if ref_val is None:
            ref_val = got
        assert got == ref_val, f"engine={engine} got={got!r} expected={ref_val!r}"


def test_compiled_function_wide_port_raises() -> None:
    """The compiled engine's `_user_func_XXX` call ABI is hardcoded to a
    single native `long long` per argument/return, at three separate
    points (the generated C signature, the port-binding write inside the
    function body, and the return statement) -- there is no multi-word
    representation anywhere in it, unlike every other "wide value in
    narrow context" bug fixed this wave (those were routing gaps around
    already-correct wide storage/computation; here there is no wide
    storage for a function argument/return to reach at all). A function
    port or return wider than 64 bits is therefore unconditionally
    unrepresentable, regardless of the calling context's own width.
    Rather than silently corrupt the value (confirmed against Icarus:
    `compiled` previously gave a wrong result where reference/vm/vm-fast
    agreed), the compiled engine now fails loudly at codegen time.
    """
    source_wide_port = """
module t(a);
    input [70:0] a;
    function [7:0] fn_narrow(input [70:0] p);
        begin
            fn_narrow = p[7:0];
        end
    endfunction
    wire [7:0] y = fn_narrow(a);
endmodule
"""
    source_wide_ret = """
module t(a);
    input [7:0] a;
    function [70:0] fn_wide_ret(input [7:0] p);
        begin
            fn_wide_ret = p;
        end
    endfunction
    wire [70:0] y = fn_wide_ret(a);
endmodule
"""
    for source in (source_wide_port, source_wide_ret):
        with pytest.raises(NotImplementedError, match="wider than 64 bits"):
            td._sim_for(source, "compiled")


def _assert_all_engines_agree(source: str, drives: dict) -> None:
    """Shared helper: drive `drives` on all engines, assert every signal
    read from ENGINES agrees with reference. `drives` maps signal name to
    (value, width) or (value, width, mask).
    """
    ref_result = None
    for engine in ENGINES:
        sim = td._sim_for(source, engine)
        sim.drive("clk", td.Value(0, width=1))
        for name, width, _signed in td.FIXED_SIGNALS:
            sim.drive(name, td.Value(0, width=width))
        sim.settle()
        for name, spec in drives.items():
            val, width = spec[0], spec[1]
            mask = spec[2] if len(spec) > 2 else 0
            sim.drive(name, td.Value(val, width=width, mask=mask))
        sim.settle()
        result = {name: sim.read(name) for name in ("y0", "y1") if f"output [63:0] {name}" in source}
        if ref_result is None:
            ref_result = result
        for name, got in result.items():
            assert got == ref_result[name], f"engine={engine} {name}: got={got!r} expected={ref_result[name]!r}"


def test_compiled_natural_width_op_wide_operand_mask() -> None:
    """Regression test for a family of confirmed compiled-engine mask
    bugs in `_emit_mask_expr`'s `_NATURAL_WIDTH_OPS` (comparisons/`&&`/
    `||`/bitwise) handling:

    1. `==`/`!=`/`&&`/`||`'s genuinely-ambiguous case returned the raw
       `lm | rm` operand-mask pattern directly instead of collapsing it
       to the literal `1` (these ops are self-determined to exactly 1
       bit, so their mask must be too) -- confirmed for `(a2 == a3)`
       with `a3` entirely x.
    2. The op_width GATE controlling that computation only widened for
       `_COMPARISON_OPS`, leaving bitwise `&`/`|` computing their own
       operand masks at the OUTER context width instead of their own
       combined `max(left, right)` width (unlike the VALUE side, which
       always uses the broader `_NATURAL_WIDTH_OPS`) -- confirmed for
       `(fn_sub16s(...) | $signed(a3))` with `a3` (63 bits) entirely x.

    Confirmed against Icarus (cross-engine): reference/vm/vm-fast agree;
    only compiled disagreed before these fixes.
    """
    source = """
module t(
    input clk,
    input signed [0:0] a0,
    input [7:0] a1,
    input signed [15:0] a2,
    input [62:0] a3,
    input signed [63:0] a4,
    input [64:0] a5,
    input signed [79:0] a6,
    input [0:0] a7,
    output [63:0] y0,
    output [63:0] y1
);
    function signed [15:0] fn_sub16s(input signed [15:0] a, input signed [15:0] b);
        begin
            fn_sub16s = a - b;
        end
    endfunction
    assign y0 = (a2 == a3);
    assign y1 = (fn_sub16s(a2[11:10], a7) | $signed(a3));
endmodule
"""
    _assert_all_engines_agree(
        source,
        {
            "a2": (45119, 16),
            "a3": (0, 63, (1 << 63) - 1),
            "a7": (0, 1),
        },
    )


def test_compiled_nested_context_determined_operator_signedness() -> None:
    """Regression test for a confirmed compiled-engine bug: `_emit_unary`'s
    general (non-fixed-self-determined) `~`/unary-`-` handling computes
    its operand once via `_emit_expr(operand, eval_width, ...)` (already
    complete and correct at the full context width for ANY operand
    shape, per the "compute directly at the requested width" convention
    this file relies on), then REDUNDANTLY re-applied `_sign_ext(operand,
    ow)` using the operand's own bare self-width `ow` -- a true no-op for
    a plain Identifier operand (whose own `_emit_expr` already performed
    the identical extension), but actively WRONG for a COMPOUND operand
    (e.g. a further UnaryOp `-`), whose value at `eval_width` is a
    genuinely COMPUTED result, not "a raw `ow`-bit value with unfilled
    upper bits" -- reinterpreting its own bit 0 as an unfilled sign bit
    to propagate corrupts an already-correct value.

    Confirmed against Icarus (cross-engine) for `(-(-a0))` with `a0` a
    signed 1-bit `-1` (raw bit `1`) assigned into a 64-bit destination:
    reference/vm/vm-fast all correctly negate twice back to `+1`
    (sign-extended); compiled corrupted the inner `-a0`'s own clean
    result before the outer `-` ran.
    """
    source = """
module t(
    input clk,
    input signed [0:0] a0,
    input [7:0] a1,
    input signed [15:0] a2,
    input [62:0] a3,
    input signed [63:0] a4,
    input [64:0] a5,
    input signed [79:0] a6,
    input [0:0] a7,
    output [63:0] y0,
    output [63:0] y1
);
    assign y0 = (-(-a0));
    assign y1 = (~a0);
endmodule
"""
    _assert_all_engines_agree(source, {"a0": (1, 1)})


def test_compiled_wide_arithmetic_function_argument() -> None:
    """Regression test for a confirmed compiled-engine bug:
    `_emit_user_func_call_expr` always computed each argument via the
    plain narrow `_emit_expr`/`_emit_mask_expr` at the PORT's own
    declared width -- correct for most shapes (the generated function
    helper re-masks the incoming value to the port's real width anyway),
    but wrong for a context-determined arithmetic argument (`%`/`/` in
    particular, NOT "residue-safe": `(a % b) mod N != ((a mod N) % (b
    mod N)) mod N`) whose OWN operand is wider than 64 bits -- computing
    the modulo directly at the narrow port width first truncates the
    DIVIDEND before the remainder is even determined, giving an entirely
    different (wrong) result than computing the full-precision modulo
    first and only THEN taking its low bits for the port.

    Confirmed against Icarus (cross-engine) for `fn_add8({2{{2{a0}}}},
    (a6 % (a4[28:22] | 1)))` with `a6` 80 bits bound to an 8-bit port:
    reference/vm/vm-fast agree; only compiled disagreed before the fix
    (`_emit_wide_arg_to_value`, routing the argument through the wide
    emitter whenever its own internal computation exceeds 64 bits).
    """
    source = """
module t(
    input clk,
    input signed [0:0] a0,
    input [7:0] a1,
    input signed [15:0] a2,
    input [62:0] a3,
    input signed [63:0] a4,
    input [64:0] a5,
    input signed [79:0] a6,
    input [0:0] a7,
    output [63:0] y0
);
    function [7:0] fn_add8(input [7:0] a, input [7:0] b);
        begin
            fn_add8 = a + b;
        end
    endfunction
    assign y0 = {2{fn_add8({2{{2{a0}}}}, (a6 % (a4[28:22] | 1)))}};
endmodule
"""
    _assert_all_engines_agree(
        source,
        {
            "a0": (1, 1),
            "a4": (7571520453935328720, 64),
            "a6": (725654678142160021167080, 80),
        },
    )


def test_compiled_ternary_own_signed_ignores_inherited_override() -> None:
    """Regression test for a confirmed compiled-engine bug:
    `_emit_ternary_value_mask_exprs`'s `own_signed` (the ternary's own
    combined signedness, threaded into its branches as `t_signed_
    override`/`f_signed_override`) let an inherited `signed_override`
    parameter WIN over the ternary's own fresh computation from its two
    branches -- unlike `sim/evaluator.py`'s TernaryOp handling, which
    ALWAYS computes `own_signed` fresh, unconditionally ignoring any
    inherited override ("This establishes a *fresh* override for both
    branches, replacing whatever override... was active from further
    out").

    The letting-override-win design was itself a deliberate, previously
    confirmed fix for `(a0 <= (a2 ? a0 : a6))` (`a0`, `a6` both declared
    signed) -- but that case's inherited override and the ternary's own
    fresh computation happen to independently agree (both `True`) for
    that specific shape, making the two designs indistinguishable there.
    They diverge for a ternary that is the operand of a UnaryOp `-`,
    itself a branch of an OUTER ternary with a DIFFERENT combined
    signedness: the INNER ternary's own fresh signedness must win,
    exactly as the always-fresh reference behavior gives.

    This test covers BOTH confirmed shapes (`y0`: the original
    letting-override-win fix; `y1`: the case that fix's design got
    wrong) to guard against a future change re-introducing either
    direction of this bug. Confirmed against Icarus (cross-engine):
    reference/vm/vm-fast agree on both; only compiled disagreed on `y1`
    before this fix.
    """
    source = """
module t(
    input clk,
    input signed [0:0] a0,
    input [7:0] a1,
    input signed [15:0] a2,
    input [62:0] a3,
    input signed [63:0] a4,
    input [64:0] a5,
    input signed [79:0] a6,
    input [0:0] a7,
    output [63:0] y0,
    output [63:0] y1
);
    function [7:0] fn_add8(input [7:0] a, input [7:0] b);
        begin
            fn_add8 = a + b;
        end
    endfunction
    assign y0 = (a0 <= (a2 ? a0 : a6));
    assign y1 = fn_add8({3{a4}}, (a3[35] ? (-(a1 ? a0 : a0)) : ($unsigned(a7) << (!a2[4]))));
endmodule
"""
    for engine in ENGINES:
        sim = td._sim_for(source, engine)
        sim.drive("clk", td.Value(0, width=1))
        for name, width, _signed in td.FIXED_SIGNALS:
            sim.drive(name, td.Value(0, width=width))
        sim.settle()
        sim.drive("a0", td.Value(1, width=1))
        sim.drive("a1", td.Value(89, width=8))
        sim.drive("a2", td.Value(52297, width=16))
        sim.drive("a3", td.Value(1067708165146980894, width=63))
        sim.drive("a4", td.Value(7429227395453986858, width=64))
        sim.drive("a6", td.Value(1026619480069701007101656, width=80))
        sim.drive("a7", td.Value(0, width=1, mask=1))
        sim.settle()
        y0, y1 = sim.read("y0"), sim.read("y1")
        assert y0 == td.Value(1, width=64), f"engine={engine} y0={y0!r}"
        assert y1 == td.Value(43, width=64), f"engine={engine} y1={y1!r}"


def test_compiled_wide_concat_in_narrow_context_not_truncated() -> None:
    """Regression test guarding the `notes/known_issues.md` "residual
    gap" note about `_emit_concat`/`_emit_replication`'s narrow-path
    `if shift >= 64: continue` line: a genuinely wide (>64-bit)
    concatenation embedded as a ternary's CONDITION, or inside a
    comparison passed as a function-call argument, both under an
    otherwise-narrow destination.

    Investigation found this scenario is NOT reachable in practice given
    the current routing: any Concatenation whose own combined width
    exceeds 64 bits already reports that width via `_expr_width`
    (`sum(part widths)`), which `_expr_max_internal_width` folds into its
    own `max(...)` at every level of the recursion -- so `_rhs_needs_
    wide_eval` (statement-level), `_emit_wide_truthy_to_value` (ternary
    condition), `_emit_wide_binary_to_value` (comparison operand), and
    `_emit_wide_arg_to_value` (function-call argument) all correctly
    route such a concatenation through the wide scratch-based emitter
    -- which has its own dedicated `Concatenation`/`Replication` handling
    in `_wide_emitter.py` -- before `_emit_concat`'s narrow path (whose
    `shift` can only ever reach 64 when the concatenation's own total
    width already exceeds 64, i.e. exactly when it's unreachable) is
    ever invoked. Confirmed against Icarus (cross-engine): reference/vm/
    vm-fast/compiled all already agree on both shapes below -- this test
    exists purely to pin that agreement as a regression guard rather
    than to fix a live bug.
    """
    source = """
module t(
    input clk,
    input signed [0:0] a0,
    input [7:0] a1,
    input signed [15:0] a2,
    input [62:0] a3,
    input signed [63:0] a4,
    input [64:0] a5,
    input signed [79:0] a6,
    input [0:0] a7,
    output [63:0] y0,
    output [63:0] y1
);
    function [7:0] fn_sel(input [7:0] a, input b);
        begin
            fn_sel = b ? a : ~a;
        end
    endfunction
    assign y0 = (({a6, a1}) ? a2[7:0] : a3[7:0]);
    assign y1 = fn_sel(a3[7:0], (({a6, a1}) > 0));
endmodule
"""
    for engine in ENGINES:
        sim = td._sim_for(source, engine)
        sim.drive("clk", td.Value(0, width=1))
        for name, width, _signed in td.FIXED_SIGNALS:
            sim.drive(name, td.Value(0, width=width))
        sim.settle()
        sim.drive("a1", td.Value(0, width=8))
        sim.drive("a2", td.Value(52301, width=16))
        sim.drive("a3", td.Value(1067708165146980894, width=63))
        sim.drive("a6", td.Value(1 << 60, width=80))
        sim.settle()
        y0, y1 = sim.read("y0"), sim.read("y1")
        assert y0 == td.Value(77, width=64), f"engine={engine} y0={y0!r}"
        assert y1 == td.Value(30, width=64), f"engine={engine} y1={y1!r}"
